version: '3.9'

services:
  airflow-web:
    build: .
    image: airflow-custom:2.9.0
    container_name: airflow_web
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      GROQ_API_KEY: ${GROQ_API_KEY}
      S3_ENDPOINT: http://host.docker.internal:9000
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: >
      bash -c "airflow db init && airflow webserver"

  airflow-scheduler:
    image: airflow-custom:2.9.0
    container_name: airflow_scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      GROQ_API_KEY: ${GROQ_API_KEY}
      S3_ENDPOINT: http://host.docker.internal:9000
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "airflow scheduler"

volumes:
  airflow_home: